### ISSUE TITLE
React Native Compatibility

### ISSUE THREAD

**Issue by jacobdfriedmann** [addthis/fluxthis#102]
Was playing with react native recently and attempted to use fluxthis because I like it. There are only a couple things (one important one) that would need to be changed in order to make it compatible. I even think the APIActionCreators will work because react-native polyfills xhr. However, `ActionCreator` pulls in `react/lib/ReactPropTypes` for payloadType validation. This obviously won't work in a react native project which would need to require something like `require('react-native').PropTypes` instead.

Not sure if there is a good way (or a convention) to have this dual peer dependency on react OR react-native, but it seems like there should be an easy way to achieve this. Just thought I'd open it up to conversation.

**Comment by jhorwit2** [comment]
I think the only solution would be to publish react-native specific versions along with our normal releases. Not 100% sure how react native works, but I assume you can select the version to install?

**Comment by AlanFoster** [comment]
Slightly crazy suggestion -

Could we make use of peer dependencies here?

ie, create a new npm module `fluxthis-prop-types` for wrapping PropTypes, release two specific branch versions for `react-native` and `react-dom`, then specify `fluxthis-prop-types` as a peer dependency, defaulting to the `react-dom` branch version. If a developer wants to change this to use react-native proptypes, they will specify in their package.json that they want the react-native wrapper branch instead

**Comment by jmrog** [comment]
Looking quickly through the source, I think @jacobdfriedmann is right that the dependency on `react/lib/ReactPropTypes` is the main issue. FluxThis only uses that for payload validation, I think (and only in dev environments), so I think it's really worth considering making that an optional dependency. It might even be as simple as putting the relevant `require` in a try-catch block (maybe first trying to require from `react`, then trying to require from `react-native`, and then giving up), making the validation parts in `ActionCreator` conditional on the presence of `PropTypes`, and possibly issuing a warning message to the user if no supplier of `PropTypes` is found.

**Comment by jmrog** [comment]
I finally got a chance do some playing around with this tonight. @jacobdfriedmann, do you recall what the original problem was when you created this issue? I ask because I was actually able to get FluxThis working with React Native without any real tinkering at all. Things I tested: APIActionCreator with a request to a NodeJS endpoint that I quickly whipped up, plain old ActionCreator, and ImmutableStore. They all essentially "just worked" (even the validation of payloadTypes; see the second screenshot below).

One possible caveat is that I required the pre-built version of FluxThis; not sure how things would go with the uncompiled version.

<img width="1076" alt="screen shot 2015-12-22 at 8 55 57 pm" src="https://cloud.githubusercontent.com/assets/8409748/11969891/573ac7ea-a8ef-11e5-90bc-ec49616980d4.png">

<img width="464" alt="screen shot 2015-12-22 at 8 57 21 pm" src="https://cloud.githubusercontent.com/assets/8409748/11969893/5d3a2294-a8ef-11e5-860d-cc493e523fee.png">

**Comment by jacobdfriedmann** [comment]
You're right...this isn't a problem if you use the prebuilt version, which comes packaged with the PropTypes module. I was requiring the source files. I guess there is no real need for me to do that. I'll close this.

**Comment by jmrog** [comment]
This is also worth noting. It sounds like you might be able to require the source files without issue very soon. https://github.com/facebook/react-native/issues/2985
