### ISSUE TITLE
Combining ApiActionCreator and compnentDidUpdate

### ISSUE THREAD

**Issue by AlanFoster** [addthis/fluxthis#111]
We are currently using an infinite loading component in conjunction with an ApiActionCreator, and we are hitting the invariant issue `Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch` from fluxthis.

We are hitting this invariant when an ApiActionCreator returns fires a success event, which populates a store, and then hydrates the infinite loading component. This component then triggers the ApiActionCreator again within its `componentDidUpdate` lifecycle method. 

This is somewhat unfortunate, as internally `this[IS_DISPATCHING]` is still set to true when the child component's componentDidUpdate is called - and thus triggering this invariant. We are currently working around this issue with a setTimeout/_.defer around the ApiActionCreator call - but is there something nicer that can be done? Is this invariant supposed to trigger? Is it bad practice to hook into callbacks to request more data within a `componentDidUpdate` method?

**Comment by jhorwit2** [comment]
Are you using the router?

**Comment by AlanFoster** [comment]
@jhorwit2 No - we're not currently using a router. We're directly using the store's mixin into a top-level component which implements `getStateFromStores`. On API success we populate the store, which populates the infinite component. Then the infinite component then requests more data within its `componentDidUpdate` and this invariant is triggered

**Comment by jhorwit2** [comment]
AFAIK the invariant is not suppose to be triggered on `componentDidUpdate`. I know internally we have calls in `componentDidMount` which is essentially equivalent. I do know the FluxThis router has some caveats to that which is why I asked if you were using it. We will look into why this is happening.

**Comment by mako-taco** [comment]
You should not be creating any actions inside `componentDidUpdate`, because that could create an infinite cycle.  That is why the invariant is thrown.

```
User interaction creates Action A
Component B Updates
Component B Creates Action A
Component B Updates
Component B Creates Action A
...
```

Instead, you could consider creating the action inside the `handleSuccess` or `handleFailure` callbacks of the APIActionCreator for Action A.  Let me know if that solution works for you.

**Comment by AlanFoster** [comment]
@mako-taco The infinite component will only trigger an action from its `componentDidMount` when it is able to visually display new rows. 

With the current setup, the infinite component is the size of the window which is able to display 30 rows. On `componentDidMount` we trigger the API Action requesting the next batch of 20 rows. On success the `componentDidUpdate` method decides it could handle another 10, so it triggers another API Action. However due to the invariant issue, fluxthis will error here. However, if we wrap this API Action in a `setTimeout`, we will populate the infinite component the next 20 rows. The infinite component will then no longer request any more rows, as it is sated. Therefore in total there will only be 2 API actions triggered in total.

```
User loads page
Component B Mounts - Creates Action A
Component B Updates
Component B Creates Action A
Component B Updates
No further Actions sent
```

Since the API requests are decided at the view level, we wouldn't be able to move this logic into the `handleSuccess` or `handleFailure` methods.

**Comment by mako-taco** [comment]
I was trying to illustrate that triggering an action inside of `componentDidUpdate` will and should _always_ trigger an invariant, if the component is updating due to a previous dispatch, because of the possibility of an infinite cycle.  You'd need special logic inside of `componentDidUpdate` to prevent this cycle (which it sounds like you have, but no flux framework could know this).

Is it possible for you to make all of the initial requests inside of `componentDidMount`, and then any initial requests would be triggered off of a scroll event?

**Comment by jmrog** [comment]
As @mako-taco is indicating, this is by design, and I think it is the intended pattern for any Flux application (I think you'll get the same invariant violation using vanilla Flux, in fact). In [one of his oft-cited Stack Overflow answers](http://stackoverflow.com/questions/26581587/flux-dispatch-dispatch-cannot-dispatch-in-the-middle-of-a-dispatch), Bill Fisher (one of the maintainers of Flux) says, "Components should not be deciding when to fetch data. This is application logic in the view layer. This logic belongs in the store, which can fire off the XHR and then the error/success callback create actions with the new data." The same thing is indicated in [Facebook's diagram of the Flux data flow](http://facebook.github.io/react/blog/2014/07/30/flux-actions-and-the-dispatcher.html#actions-and-actioncreators), where action creators are only involved as the result of user interactions or API calls (there is no direct path from the view to the AC).

**Comment by jhorwit2** [comment]
@jmrog there are two views on where to load data. You can listen to talks one store vs view from the react conference. Both are technically correct.

**Comment by jmrog** [comment]
@jhorwit2 Interesting; I had been taking Bill Fisher's word as "law" on this, but I guess it isn't (or maybe he was talking about a more specific scenario -- the gist he was commenting on doesn't actually do the action creating in `componentDidUpdate`).

**Comment by jhorwit2** [comment]
I'm closing this since this doesn't seem like an issue.
