### ISSUE TITLE
Cannot depend on core fluxthis dependency within example project

### ISSUE THREAD

**Issue by AlanFoster** [addthis/fluxthis#60]
The tutorials use the following to require modules -

```javascript
const ActionCreator = require('fluxthis/src/ActionCreator');
```

This is brittle, as it depends on the internal file structure of the fluxthis package. Instead it would be preferable to depend on the module directly -

```javascript
const ActionCreator = require('fluxthis').ActionCreator;
```

Unfortunately when requiring `fluxthis` using the given quickstart code, the following error is thrown -

```javascript
Uncaught Error: only one instance of babel/polyfill is allowed
```

**Comment by mako-taco** [comment]
The structure of the project won't change -- we actually _prefer_ you include the individual files directly.  This makes for a smaller total bundle size, as any files which you opt not to use do not get lumped in to your code.  Checkout this output of `uglifyjs` for an example:

```
//input
(function () {
	var x = (function () {
		return {
			a: 0,
			b: 1,
			c: 2
		};
	}())

	console.log(x.a);
}());

//output
!function(){var x=function(){return{a:0,b:1,c:2}}();console.log(x.a)}();
```

Notice that even though we only use `x.a`, both `x.b` and `x.c` are along for the ride.  We absolutely will not change our directory structure without a breaking version increment.  Either way, I don't see us changing the structure as all our company's web apps rely on it ;)

**Comment by jhorwit2** [comment]
Hey Alan, 

I'm curious about your error you received 

```Uncaught Error: only one instance of babel/polyfill is allowed```

Do you already require the `babel/polyfill` in your project? If so, you will need to just use the one we use. Babel has a limitation in that if you require it twice it breaks. 

As far as brittleness is concerned, this is why we have versioning and any breaking changes will be made known. We have no intentions to change structure (unless it's adding files) since we have multiple apps in production that require this schema (we only require relative paths).

**Comment by AlanFoster** [comment]
Closing as #71 resolves this issue.
