### ISSUE TITLE
Testing - Store already has already has a controller view registered

### ISSUE THREAD

**Issue by AlanFoster** [addthis/fluxthis#64]
With the example QuickStart code and the following test -

```javascript
let MyFirstStore = require('stores/MyFirstStore');
let MyFirstComponent = require('components/MyFirstComponent');
var should = require('should');

describe('My first store', () => {
  var React = require('react/addons');
  var TestUtils = React.addons.TestUtils;

  beforeEach(() => {
    MyFirstStore.TestUtils.reset();
  });

  it('allows the same component to be rendered multiple times', () => {
    var first = TestUtils.renderIntoDocument(<MyFirstComponent />);
    should(first).be.ok;

    var second = TestUtils.renderIntoDocument(<MyFirstComponent />);
    should(second).be.ok;
  })
});
```

The tests break -

![image](https://cloud.githubusercontent.com/assets/1271782/7375832/29924534-edd3-11e4-8300-0e327a6225cf.png)

I had assumed `MyFirstStore.TestUtils.reset();` may have handled this, and cleared the registered state appropriately, but that does not appear to be the case.

**Comment by jhorwit2** [comment]
I'm not quite sure that is even what you want here. You are rendering the same component twice into the document it seems, which should throw an error in FluxThis. 

`beforeEach` executes before each `it` call, so by you tried to render the component twice. 

The interesting bit of code that I'm unfamiliar with here is the `renderIntoDocument` method. I don't see anywhere in the docs that shows this unmounts the first component, so if that is the case, then this is completely expected behavior and not a bug. 

https://facebook.github.io/react/docs/test-utils.html#renderintodocument

**Comment by mako-taco** [comment]
To be clear, you can totally render the same component 2x using `renderIntoDocument` if you do it like this:
```js
it('allows the same component to be rendered multiple times', () => {
    var first = TestUtils.renderIntoDocument(<div><MyFirstComponent /><MyFirstComponent/></div>);
    should(first).be.ok;
})
```

You can also use `TestUtils.scryRenderedComponentsWithType` to assert that there are two instances of `MyFirstComponent` inside of `first`.

**Comment by AlanFoster** [comment]
I unfortunately simplified the sample down to try and make it more clear, and as such the original intent of the test was lost.

But it's clear that this is not a fluxthis concern, and is instead how TestUtils renders onto the document and doesn't clean up using `componentWIllUnmount` during tests - thanks!
