### ISSUE TITLE
Router is a part of a Flux architecture?

### ISSUE THREAD

**Issue by max107** [addthis/fluxthis#94]
Move component to other repository. Router it's not a flux, i think.

**Comment by jhorwit2** [comment]
The flux architecture is simple just `views` -> `actions` -> `dispatcher` -> `stores` -> `views` and repeat. Our router works with the flux architecture and which is why it's included here. The router itself is a store with actions. We could discuss moving it to another repository, but how our builds are setup you don't need to require it (which is just like it's not there)

**Comment by max107** [comment]
Ok, thanks
